### ISSUE TITLE
Google 맞춤 검색을 추가 한다.

### ISSUE THREAD

**Issue by yundream** [golangkorea/golangkorea-hugo#3]
Google 맞춤 검색을 Github page에 통합한다. 검색 결과는 golangkorea 에 출력된다.
순수 자바 스크립트로 작동하기 때문에, github page 연동에 문제 없이 붙일 수 있다.

**Comment by yundream** [comment]
`<script>
  (function() {
    var cx = '002661009167463862046:hk6lhiihuma';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>`
이 코드 넣으면 오버레이 검색창이 뜹니다. 페이지 레이아웃에 넣는 작업이 필요 할 것 같습니다.

**Comment by jhonghee** [comment]
layouts/partials/navigation.html 로 삽입합니다.

CSS는 Hugo-Octopress에 있는 스타일을 가능하면 재 사용하겠습니다.

**Comment by jhonghee** [comment]
CSE style has been fixed and pushed.

**Comment by jhonghee** [comment]
Moved all CSS override to custom.css and remove the hugo-octopress.css from the static folder.

**Comment by yundream** [comment]
수고 하셨습니다. CSS 적용된거 확인 하고 닫겠습니다.

**Comment by yundream** [comment]
와우 멋지네요.
